# Generated by Django 4.2.3 on 2023-07-12 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dexmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrcDex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dexmanager.srcdex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Dex',
        ),
        migrations.AddField(
            model_name='srcdex',
            name='watching_users',
            field=models.ManyToManyField(blank=True, related_name='watching_dex', through='dexmanager.UserDex', to=settings.AUTH_USER_MODEL),
        ),
    ]
