# Generated by Django 4.2.3 on 2023-07-20 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0003_rename_dex_userdex_srcdex'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcdex',
            name='category',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='closing',
            field=models.CharField(default='1000', max_length=256),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='isInvest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='tags',
            field=models.JSONField(blank=True, default={'1': 123, '2': 342, '3': 152}, null=True),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='srcdex',
            name='values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
