# Generated by Django 4.2 on 2023-07-14 14:48

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dexmanager', '0004_remove_srcdex_watching_users_srcdex_closing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcdex',
            name='category',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='isInvest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='srcdex',
            name='watching_users',
            field=models.ManyToManyField(blank=True, related_name='watching_dex', through='dexmanager.UserDex', to=settings.AUTH_USER_MODEL),
        ),
    ]
