# Generated by Django 4.2 on 2023-07-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0005_srcdex_category_srcdex_description_srcdex_isinvest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcdex',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
