# Generated by Django 4.2 on 2023-07-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0006_srcdex_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srcdex',
            name='tags',
            field=models.JSONField(blank=True, default={'1': 123, '2': 342, '3': 152}, null=True),
        ),
    ]
