# Generated by Django 4.2 on 2023-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0007_alter_srcdex_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srcdex',
            name='tags',
            field=models.TextField(blank=True, default={'1': 123, '2': 342, '3': 152}, null=True),
        ),
    ]
