# Generated by Django 4.2 on 2023-07-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0004_srcdex_category_srcdex_closing_srcdex_description_and_more'),
        ('dexmanager', '0008_alter_srcdex_tags'),
    ]

    operations = [
    ]
