# Generated by Django 4.2.3 on 2023-07-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0009_merge_20230720_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srcdex',
            name='tags',
            field=models.TextField(blank=True, default={'1': 123, '2': 342, '3': 152}, null=True),
        ),
    ]
