# Generated by Django 4.2.3 on 2023-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0011_alter_srcdex_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcdex',
            name='search_keyword',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
