# Generated by Django 4.2.3 on 2023-07-24 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0012_srcdex_search_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='HankyungTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.IntegerField(default=1)),
            ],
        ),
    ]
