# Generated by Django 4.2.3 on 2023-07-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0013_hankyungtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcdex',
            name='unit',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='srcdex',
            name='category',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='srcdex',
            name='closing',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='srcdex',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='srcdex',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
