# Generated by Django 4.2.3 on 2023-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0014_srcdex_unit_alter_srcdex_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hankyungtitle',
            name='page',
        ),
        migrations.AddField(
            model_name='hankyungtitle',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
