# Generated by Django 4.2.3 on 2023-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0015_remove_hankyungtitle_page_hankyungtitle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcdex',
            name='reduced_title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
