# Generated by Django 4.2.3 on 2023-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0016_srcdex_reduced_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcdex',
            name='period',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
