# Generated by Django 4.2.3 on 2024-04-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dexmanager', '0011_alter_srcdex_tags'),
        ('dexmanager', '0017_srcdex_period'),
    ]

    operations = [
    ]
