# Generated by Django 4.2 on 2023-07-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indicator',
            new_name='Index',
        ),
    ]
